### ISSUE TITLE
Recompilation fails running Quarkus project

### ISSUE THREAD

**Issue by mshabarov** [vaadin/quarkus#48]
It should be noted in the [documentation](https://vaadin.com/docs/latest/flow/integrations/quarkus/#quarkus.vaadin.limitations) that the Quarkus reload works when the changes are saved and the page is refreshed, so no build/rebuild are needed.

Using 'Rebuild Project' in IntelliJ IDEA (and likely in another IDEs) when making a Java changes in Quarkus-based projects (example project is here https://github.com/vaadin/base-starter-flow-quarkus) and further refresh of the browser page, leads to the following error in Quarkus:
![Screenshot 2021-10-26 at 16 13 40](https://user-images.githubusercontent.com/61410877/139041785-abf2150e-add1-4795-9171-a3c24a946543.png).

**Comment by mcollovati** [comment]
Can't get to reproduce the error with latest Vaadin Quarkus extension. 
Manual browser refresh after compiling single file or rebuilding whole project works fine.
So, at the moment, documentation is in sync with actual behaviour.

Good news is that with @mvysny workaround at https://github.com/urosporo/vaadin-quarkus-extension-parent/pull/11, automatic browser refresh seems to work for frontend file changes.
However @Push does not work, because VaadinSession is always null in `PushHandler`, and this leads to and infinite reconnection loop.

**Comment by mcollovati** [comment]
This may be closed, since the documentation has been updated with a `Live Reload` section
